export const raceMethods = {
    getBlockHeight: {
        defaultParams: {},
        name: "getBlockHeight",
        optionalParams: ["commitment", "minContextSlot"],
        paramsFormat: "none",
    },
    getBlockProduction: {
        defaultParams: {},
        name: "getBlockProduction",
        optionalParams: ["commitment", "identity", "range"],
        paramsFormat: "none",
    },
    getClusterNodes: {
        defaultParams: {},
        name: "getClusterNodes",
        optionalParams: [],
        paramsFormat: "none",
    },
    getEpochInfo: {
        defaultParams: {},
        name: "getEpochInfo",
        optionalParams: ["commitment", "minContextSlot"],
        paramsFormat: "none",
    },
    getEpochSchedule: {
        defaultParams: {},
        name: "getEpochSchedule",
        optionalParams: [],
        paramsFormat: "none",
    },
    getFirstAvailableBlock: {
        defaultParams: {},
        name: "getFirstAvailableBlock",
        optionalParams: [],
        paramsFormat: "none",
    },
    getGenesisHash: {
        defaultParams: {},
        name: "getGenesisHash",
        optionalParams: [],
        paramsFormat: "none",
    },
    getHealth: {
        defaultParams: {},
        name: "getHealth",
        optionalParams: [],
        paramsFormat: "none",
    },
    getHighestSnapshotSlot: {
        defaultParams: {},
        name: "getHighestSnapshotSlot",
        optionalParams: [],
        paramsFormat: "none",
    },
    getIdentity: {
        defaultParams: {},
        name: "getIdentity",
        optionalParams: [],
        paramsFormat: "none",
    },
    getInflationRate: {
        defaultParams: {},
        name: "getInflationRate",
        optionalParams: [],
        paramsFormat: "none",
    },
    getLatestBlockhash: {
        defaultParams: {},
        name: "getLatestBlockhash",
        optionalParams: ["commitment", "minContextSlot"],
        paramsFormat: "none",
    },
    getLeaderSchedule: {
        defaultParams: {},
        name: "getLeaderSchedule",
        optionalParams: ["epoch", "commitment", "identity"],
        paramsFormat: "none",
    },
    getMaxRetransmitSlot: {
        defaultParams: {},
        name: "getMaxRetransmitSlot",
        optionalParams: [],
        paramsFormat: "none",
    },
    getMaxShredInsertSlot: {
        defaultParams: {},
        name: "getMaxShredInsertSlot",
        optionalParams: [],
        paramsFormat: "none",
    },
    getSlot: {
        defaultParams: {},
        name: "getSlot",
        optionalParams: ["commitment", "minContextSlot"],
        paramsFormat: "none",
    },
    getSlotLeader: {
        defaultParams: {},
        name: "getSlotLeader",
        optionalParams: ["commitment", "minContextSlot"],
        paramsFormat: "none",
    },
    getStakeMinimumDelegation: {
        defaultParams: {},
        name: "getStakeMinimumDelegation",
        optionalParams: ["commitment"],
        paramsFormat: "none",
    },
    getSupply: {
        defaultParams: {},
        name: "getSupply",
        optionalParams: ["commitment", "excludeNonCirculatingAccountsList"],
        paramsFormat: "none",
    },
    getTransactionCount: {
        defaultParams: {},
        name: "getTransactionCount",
        optionalParams: ["commitment", "minContextSlot"],
        paramsFormat: "none",
    },
    getVersion: {
        defaultParams: {},
        name: "getVersion",
        optionalParams: [],
        paramsFormat: "none",
    },
    minimumLedgerSlot: {
        defaultParams: {},
        name: "minimumLedgerSlot",
        optionalParams: [],
        paramsFormat: "none",
    },
};
